### PR TITLE
Fix handleGRPC panic on sending to closed channel

### LINKED ISSUE #13: handleGRPC can panic
[`(*mux).handleGRPC(..)`](https://github.com/elastic/gmux/blob/main/mux.go#L299) occasionally panics with following error:

```
http: panic serving <ip:port>: send on closed channel
goroutine 3386993 [running]:
net/http.(*conn).serve.func1()
	net/http/server.go:1825 +0xbf
panic({0x557013b82be0, 0x557013f70d50})
	runtime/panic.go:844 +0x258
github.com/elastic/gmux.(*mux).handleGRPC(0x0?, 0x60?, {0x557013f99500?, 0xc0021f0cc0?}, 0xc003e135c0, {0x557013db38c0?, 0xc001fe1201?})
	github.com/elastic/gmux@v0.2.0/mux.go:300 +0x7d
github.com/elastic/gmux.(*mux).handleH2(0x20?, 0xc0000b8800?, {0x557013f98e20?, 0xc0007a0380?}, {0x557013f7a528, 0xc001fe1200})
	github.com/elastic/gmux@v0.2.0/mux.go:138 +0x519
github.com/elastic/gmux.ConfigureServer.func1(0xc002a3ab60, 0xc0007a0380, {0x557013f7a528?, 0xc001fe1200?})
	github.com/elastic/gmux@v0.2.0/mux.go:79 +0x51
net/http.(*conn).serve(0xc0027acb40, {0x557013f92370, 0xc004642180})
	net/http/server.go:1874 +0x1293
created by net/http.(*Server).Serve
	net/http/server.go:3071 +0x4db
```

I have not yet found how to reproduce it.

### PR DESCRIPTION
**Pull request by carsonip**
Closes #13

### CODE REVIEW

File: conn.go [hunk 1]
```diff
@@ -91,16 +92,18 @@ func (l *chanListener) Addr() net.Addr {
...
 func (l *chanListener) Accept() (net.Conn, error) {
-	conn, ok := <-l.conns
-	if !ok {
+	select {
+	case <-l.closed:
 		return nil, errors.New("listener closed")
+	default:
 	}
+	conn := <-l.conns
 	return conn, nil
```
Comment (axw) [inline conn.go:107]:
```suggestion
	select {
	case <-l.closed:
		return nil, errors.New("listener closed")
	case conn := <-l.conns:
		return conn, nil
	}
```

It used to be that `<-l.conns` would return (nil, false) when the listener was closed. Because that channel is no longer closed, we'll need to select on `l.closed` whenever we try to receive from `l.conns` to prevent blocking indefinitely.

File: mux.go [hunk 2]
```diff
@@ -298,7 +298,8 @@ func (m *mux) handleHTTP(srv *http.Server, conn net.Conn, closed <-chan struct{}
 
 func (m *mux) handleGRPC(_ *http.Server, conn net.Conn, closed <-chan struct{}, _ http.Handler) error {
 	select {
-	case m.grpcConns <- conn:
+	case <-m.grpcListener.closed:
```
Comment (axw) [inline mux.go:301]: I think we should return an error here indicating that the gRPC listener has been closed.

**Review by axw — CHANGES_REQUESTED** [review]
Looks good overall, just a couple of things. Could you please add a test that closes the HTTP server before the gRPC server, like we had in APM Server?

File: mux.go (hunk 2 above)
Comment (carsonip) [reply mux.go:301]: Right. What was I thinking yesterday? :facepalm: 
Though I'll check how caller handles error in case handleGRPC returns non-nil error

File: conn.go (hunk 1 above)
Comment (carsonip) [reply conn.go:107]: Right, there may be a race if not put inside the same `select`.

File: mux.go (hunk 2 above)
Comment (carsonip) [reply mux.go:301]: The error from `handleGRPC` will be logged to `srv.ErrLog` for h2 but ignored for h2c. Will have to pass in `srv.ErrLog` to `mux.withGRPCInsecure` if we want to log the error.

Comment (axw) [reply mux.go:302]: Not super important, but sounds like a good idea.

**Review by axw — APPROVED** [review]
Looks good, thank you!

File: conn.go [hunk 3]
```diff
@@ -91,17 +92,18 @@ func (l *chanListener) Addr() net.Addr {
 
 func (l *chanListener) Close() error {
 	l.closeOnce.Do(func() {
-		close(l.conns)
+		close(l.closed)
```
Comment (kruskall) [inline conn.go:95]: *question*: can we also close `l.conns` here ? 

Will the select statement in `mux.go` always choose the `l.closed` case because the channel is closed and always available ?

**Review by kruskall — COMMENTED** [review]
Just a minor question

File: conn.go (hunk 3 above)
Comment (carsonip) [reply conn.go:95]: we actually can, I don't think it will make any difference though

Comment (carsonip) [reply conn.go:95]: but it will catch us placing stuff into conns when it is closed. I'll update the PR

Comment (axw) [reply conn.go:95]: Is that safe for `handleGRPC`? If you send to a closed channel it'll panic. Not sure off hand what happens in a select.

Comment (carsonip) [reply conn.go:95]: ha! I think @kruskall and I didn't have the right understanding of the select statement guarantees:
from https://go.dev/ref/spec#Select_statements
> If one or more of the communications can proceed, a single one that can proceed is chosen via a uniform pseudo-random selection. Otherwise, if there is a default case, that case is chosen. If there is no default case, the "select" statement blocks until at least one of the communications can proceed. 

So @axw is right, it will panic because select priority is not guaranteed. I'll revert the commit.

Comment (carsonip) [reply conn.go:95]: Unfortunately it also means that we do not reliably return `errors.New("grpc listener closed")`.

**Review by kruskall — APPROVED** [review]
