### PR TITLE
fix: mirror backend initial HTTP/2 settings to avoid illegal SETTINGS change

### LINKED ISSUE #20887: HTTP/2 connection error from 8.19.12, 9.2.6, 9.3.1
**APM Server version** (`apm-server version`): from 9.2.6 to 9.3.1 (probably further versions)

**Description of the problem including expected versus actual behavior**: Starting from the version 9.2.6 there is reproducible HTTP/2 error when connecting to APM Server. There is a framing error reported by cURL and zabbix-proxy in my environment, but error is the same: `

**Steps to reproduce**:

 1. Deploy APM Server and Elasticsearch 9.2.5 in Kubernetes cluster.
 2. Access APM Server from your machine via port-forwarding or from an another container. The request must succeed.
 3. Upgrade APM Server to 9.2.6 or upper (up to 9.3.1).
 4. Access APM Server from your machine via port-forwarding or from an another container. The request will fail with a HTTP/2 error.

**Provide logs (if relevant)**:

<details>

<summary>cURL request to `9.2.5` (port-forwarding)</summary>

```
✦ ❯ curl -vk https://localhost:8200/
* Host localhost:8200 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:8200...
* Connected to localhost (::1) port 8200
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256 / [blank] / UNDEF
* ALPN: server accepted h2
* Server certificate:
*  subject: OU=main-apm-server; CN=main-apm-server-apm-http.apm.apm.local
*  start date: Apr 14 07:05:51 2026 GMT
*  expire date: Apr 14 07:15:51 2027 GMT
*  issuer: OU=main-apm-server; CN=main-apm-server-http
*  SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://localhost:8200/
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: localhost:8200]
* [HTTP/2] [1] [:path: /]
* [HTTP/2] [1] [user-agent: curl/8.7.1]
* [HTTP/2] [1] [accept: */*]
> GET / HTTP/2
> Host: localhost:8200
> User-Agent: curl/8.7.1
> Accept: */*
>
* Request completely sent off
< HTTP/2 200
< x-content-type-options: nosniff
< content-length: 0
< date: Tue, 14 Apr 2026 07:55:42 GMT
<
* Connection #0 to host localhost left intact
```

</details>

<details>

<summary>cURL request to `9.2.6` (port-forwarding)</summary>

```
❯ curl -vk https://localhost:8200/
* Host localhost:8200 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:8200...
* Connected to localhost (::1) port 8200
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256 / [blank] / UNDEF
* ALPN: server accepted h2
* Server certificate:
*  subject: OU=main-apm-server; CN=main-apm-server-apm-http.apm.apm.local
*  start date: Apr 14 07:05:51 2026 GMT
*  expire date: Apr 14 07:15:51 2027 GMT
*  issuer: OU=main-apm-server; CN=main-apm-server-http
*  SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://localhost:8200/
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: localhost:8200]
* [HTTP/2] [1] [:path: /]
* [HTTP/2] [1] [user-agent: curl/8.7.1]
* [HTTP/2] [1] [accept: */*]
> GET / HTTP/2
> Host: localhost:8200
> User-Agent: curl/8.7.1
> Accept: */*
>
* Request completely sent off
* Closing connection
curl: (16) Error in the HTTP2 framing layer
```

</details>

<details>

<summary>cURL request to `9.2.6` (debian pod, zabbix-proxy)</summary>

```
* Host main-apm-server:8200 was resolved.
* IPv6: (none)
* IPv4: 172.21.35.31
*   Trying 172.21.35.31:8200...
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256 / X25519MLKEM768 / RSASSA-PSS
* ALPN: server accepted h2
* Server certificate:
*  subject: OU=main-apm-server; CN=main-apm-server-apm-http.apm.apm.local
*  start date: Apr 14 07:05:51 2026 GMT
*  expire date: Apr 14 07:15:51 2027 GMT
*  issuer: OU=main-apm-server; CN=main-apm-server-http
*  SSL certificate verify result: self-signed certificate in certificate chain (19), continuing anyway.
*   Certificate level 0: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 1: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
* Connected to main-apm-server (172.21.35.31) port 8200
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://main-apm-server:8200/
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: main-apm-server:8200]
* [HTTP/2] [1] [:path: /]
* [HTTP/2] [1] [user-agent: curl/8.14.1]
* [HTTP/2] [1] [accept: */*]
> GET / HTTP/2
> Host: main-apm-server:8200
> User-Agent: curl/8.14.1
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Request completely sent off
* nghttp2 recv error -902: The user callback function failed
* Connection #0 to host main-apm-server left intact
curl: (16) nghttp2 recv error -902: The user callback function failed
```

</details>

### PR DESCRIPTION
**Pull request by carsonip**
## Problem
`gmux` sends an initial (sniffing) HTTP/2 SETTINGS frame before handing the connection to the backend `http2.Server`.

A regression was introduced in `golang.org/x/net/http2` at **`v0.50.0`** (and affects `v0.50.0+`): the server default path now sends `SETTINGS_NO_RFC7540_PRIORITIES=1` in its initial SETTINGS when using default schedulers. With connection multiplexers that already emitted an initial SETTINGS frame on the same connection, this produces a SETTINGS value change that strict clients reject (see [golang/go#77947](https://github.com/golang/go/issues/77947)).

In practice, strict HTTP/2 clients (e.g. `curl`/nghttp2, browsers in reported cases) can fail the connection after ALPN negotiates `h2` (symptoms like `curl: (56) Failure when receiving data from the peer` / framing-layer errors).

## Summary
- mirror backend `http2.Server` initial SETTINGS in gmux instead of sending an empty sniffing SETTINGS frame
- probe backend initial SETTINGS once in `ConfigureServer` via `backendInitialSettings`, store them on the mux, and reuse them for `framer.WriteSettings(m.initialSettings...)`
- fail fast in `ConfigureServer` if the probe cannot read/decode the backend initial SETTINGS
- keep probe lifecycle bounded with explicit pipe teardown and goroutine join, including a timeout guard for unexpected `ServeConn` non-return during teardown
- pin `golang.org/x/net` to `v0.50.0` in `go.mod` so tests validate behavior on the affected HTTP/2 implementation line

This addresses the HTTP/2 SETTINGS mismatch/regression tracked in [golang/go#77947](https://github.com/golang/go/issues/77947) without relying on a brittle single-setting special case.

This fix is a more future-proof and less brittle alternative to the simpler https://github.com/elastic/gmux/pull/96/changes/BASE..67188fc406f67db63ad0f7ffb04272c4a1cd1d06 , both aiming to fix https://github.com/elastic/apm-server/issues/20887

## Tests
- added `mux_internal_test.go` coverage with:
  - `TestGetConnHandlerMirrorsCustomBackendInitialSettings`
    - verifies custom backend SETTINGS are different from defaults
    - asserts `SETTINGS_MAX_CONCURRENT_STREAMS` and `SETTINGS_MAX_FRAME_SIZE` are both present when configured
    - verifies gmux mirrors the probed custom settings in its initial sniffing SETTINGS frame
- [x] `go test ./...`

## Validation notes
- local `apm-server` verification against this branch (via temporary `go.mod replace`) succeeds with `curl -vk --http2` and no framing-layer error

### CODE REVIEW

File: mux_internal_test.go [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+	"bytes"
+	"net"
+	"testing"
+	"time"
+
+	"github.com/stretchr/testify/require"
+	"golang.org/x/net/http2"
+)
+
+func TestGetConnHandlerMirrorsCustomBackendInitialSettings(t *testing.T) {
```
Comment (lahsivjar) [inline mux_internal_test.go]: While this tests does check the settings frame, I think we should be able to add a better test here. While the Go HTTP client is not a strict client it does allow us to inspect the frames over the wire. So, we should be able to test using an actual http2 server and assert the frames directly.

Something like:

1. Create an http2 server with TLS and gmux
2. Connect to the server, do h2 handshake using a raw framer (`http2.NewFramer`)
3. Send a GET request
4. Collect all frames and any GOAWAY frames from the server
5. Assert that there are no GOAWAY frames and then assert, for v0.50.0+ versions of http2, the `NO_RFC7540_PRIORITIES` frame

This test should also fail without the fix. WDYT?

**Review by lahsivjar — DISMISSED** [review]
LGTM! Need to fix the merge conflicts due to dependabot PRs. A minor comment on tests

File: mux_internal_test.go (hunk 1 above)
Comment (carsonip) [reply mux_internal_test.go]: i agree that such test would be good, but i wonder if we should instead add it to apm-server, instead of gmux. This is because there's nothing in gmux stopping apm-server from bumping to a newer x/net that breaks gmux. Now that this regression happened, and it is likely it would happen again, a test in apm-server would be able to protect us against this.

Then, do you like this new test you're proposing in only apm-server, or both apm-server and gmux?

Comment (carsonip) [reply mux_internal_test.go]: > GOAWAY frames from the server

hmm, i thought the GOAWAY frames we saw in practice are GOAWAY frames from client observed by the server, not the opposite.

Comment (lahsivjar) [reply mux_internal_test.go]: I would say both.

File: mux_internal_test.go [hunk 2]
```diff
@@ -47,10 +55,78 @@ func TestGetConnHandlerMirrorsCustomBackendInitialSettings(t *testing.T) {
...
+	var recordedConn *recordingConn
+	select {
+	case recordedConn = <-recordedConnCh:
+	default:
+		t.Fatal("missing recorded client connection")
+	}
+
+	receivedSettings, err := collectNonACKSettings(recordedConn.Bytes())
+	require.NoError(t, err)
+	require.GreaterOrEqual(t, len(receivedSettings), 2, "expected sniffing SETTINGS and backend SETTINGS")
```
Comment (lahsivjar) [inline mux_internal_test.go:124]: should we also assert that there are no GOAWAY frames?

**Review by lahsivjar — DISMISSED** [review]
LGTM!

File: mux_internal_test.go (hunk 2 above)
Comment (carsonip) [reply mux_internal_test.go:124]: done within collectNonACKSettings

File: mux.go [hunk 3]
```diff
@@ -209,6 +228,79 @@ func (m *mux) getConnHandler(conn net.Conn, buf *bytes.Buffer) (connHandlerFunc,
...
+	defer func() {
+		// Teardown everything to ensure no goroutines are left behind
+		select {
+		case err := <-clientWriteDone:
+			if err != nil && !errors.Is(err, net.ErrClosed) && !errors.Is(err, io.ErrClosedPipe) && retErr == nil {
+				retErr = fmt.Errorf("writing probe client preface/settings: %w", err)
+			}
+		case <-time.After(backendInitialSettingsTimeout):
+			if retErr == nil {
+				retErr = fmt.Errorf("probe client write timeout")
```
Comment (endorama) [inline mux.go]: We're shadowing errors with how `retErr` is reused, wouldn't be better to use `errors.Join` instead?

File: mux.go [hunk 4]
```diff
@@ -209,6 +228,80 @@ func (m *mux) getConnHandler(conn net.Conn, buf *bytes.Buffer) (connHandlerFunc,
...
+			deferErr = append(deferErr, fmt.Errorf("closing probe client pipe: %w", err))
+		}
+		select {
+		case <-serverDone:
+		case <-time.After(backendInitialSettingsTimeout): // Unexpected for conf.ServeConn to not return; fail fast
+			deferErr = append(deferErr, fmt.Errorf("serve conn timeout"))
+		}
+
+		if len(deferErr) > 0 {
+			retErr = errors.Join(append([]error{retErr}, deferErr...)...)
```
Comment (carsonip) [inline mux.go]: [to reviewer] this only run 1 time and shouldn't even happen at all, so i'm not too concerned about the perf as long as it is clear and works.

**Review by lahsivjar — DISMISSED** [review]

**Review by endorama — APPROVED** [review]
Looks good! Thanks @carsonip 🎉
